# Site
title: Code Nart
author: Kei Nart

# Linked
freecodecamp: https://freecodecamp.org/codenart
codepen: https://codepen.io/codenart
github: https://github.com/codenart
youtube: https://youtube.com
facebook: https://facebook.com

# Preference
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
